Add feature support working with multiple connections
test-fullautomation/robotframework-doip pull request #26
Opened 2024-10-15 11:04 UTC by trimai3001

2024-10-15 11:25 UTC, test-fullautomation requested changes
Hi Tri,
very good!
Please check my findings.
Thank you,
 Thomas

2024-10-15 11:25 UTC, test-fullautomation commented on config/robotframework_aio/release_items_RobotFramework_DoIP.json
> +                    "0.13." : [
Hi Tri,
this must be 0.13.1. as  0.13.0 is already released.
If 0.13.1. it will be displayed for 0.13.1. release as well as next major releasae 0.14.0. which aggregates all minor releases since 0.13.0.
Please change accordingly.
Please also add a small example here, as well as the information that the change is transparent for already existing uses of doip lib.

Same please for the latex files. Please make a bigger sample here, similar to uds documentation.

Thank you,
 Thomas

2024-10-16 10:32 UTC, trimai3001 commented
Hi Thomas,
Thank you for your findings.
I have updated it based on your feedback.
Thank you

2024-11-14 10:45 UTC, test-fullautomation commented
Hi @trimai3001 , @ngoan1608 ,
what is the status of this pull-request?
Is it ready, inclusive testing in our MPCI environment?
Thank you,
 Thomas

2024-11-14 14:01 UTC, trimai3001 commented
Hi @test-fullautomation,
Currently, the MPCI test bench has an issue with its connection to ECUs.
One rack is unable to connect, and another has an unstable connection.
I will try to test this PR tomorrow.
Thank you,
Tri

2024-11-20 10:24 UTC, test-fullautomation approved these changes
Hi Thong,
very good!
Thank you,
 Thomas

2024-11-20 10:26 UTC, merged